switch gha to pr

diff --git a/.github/workflows/print-tf-plan.yml b/.github/workflows/print-tf-plan.yml
--- a/.github/workflows/print-tf-plan.yml
+++ b/.github/workflows/print-tf-plan.yml
@@ -1,6 +1,10 @@
 name: print-tf-plan
 # TODO: switch to pr
-on: [push]
+on:
+  pull_request:
+    types:
+      - opened
+      - reopened
 permissions:
   contents: read
   id-token: write
@@ -45,61 +49,65 @@ jobs:
         uses: actions/checkout@v3
         with:
           fetch-depth: 2
-      - name: moo
-        id: moo
-        run: ${{ env.JJ_DIR }}jj.sh prepare
-  build:
-    if: ${{ !needs.prepare.outputs.workflows && needs.prepare.outputs.prefix-list-length != '0' }}
-    needs: prepare
-    runs-on: ubuntu-latest
-    env:
-      JJ_PREFIX: ""
-      JJ_REGION: "eu-central-1"
-      JJ_ROLE: "none"
-    strategy:
-      fail-fast: false
-      matrix:
-        tf: ${{ fromJson(needs.prepare.outputs.prefix-list) }}
-    steps:
-      - name: checkout
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 1
-      - name: onehundred
-        run: ${{ env.JJ_DIR }}me.sh extractMappedValues "${{ matrix.tf }}" "${{ env.JJ_DIR }}path-prefix-aws-role-mapping.json"
-      - name: fail if role not found
-        if: ${{ env.JJ_ROLE == 'none' }}
-        # TODO: create issue before exiting => should not block workflow runs
-        run: exit 1
-      - name: install stuff
+      - name: print stuff
         run: |
-          brew install tfenv
-          tfenv install 1.1.8
-          tfenv use 1.1.8
-      - name: yo
-        run: |
-          echo "${{ env.JJ_MODE }}"
-          echo "${{ env.JJ_REGION }}"
-          echo "${{ env.JJ_ROLE }}"
-          echo "${{ matrix.tf }}"
-      - name: assume role
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          role-to-assume: ${{ env.JJ_ROLE }}
-          aws-region: ${{ env.JJ_REGION }}
-      - name: create tf plan
-        run: |
-          cd ${{ matrix.tf }}
-          terraform init
-          terraform plan -lock=false > plan.txt
-          cat plan.txt
-      - name: jj-prefix
-        run: |
-          export JJ_TEMP=$(echo ${{ matrix.tf }} | sed -E 's%/%-%g')
-          echo "JJ_PREFIX=$JJ_TEMP" >> "$GITHUB_ENV"
-      - name: store tf plan
-        uses: actions/upload-artifact@v3
-        with:
-          name: ${{ env.JJ_PREFIX }}plan.txt
-          path: ${{ matrix.tf }}plan.txt
-          retention-days: 1
+          echo '${{ github.event.pull_request.head.sha }}'
+          echo '${{ env.GITHUB_SHA }}'
+#      - name: moo
+#        id: moo
+#        run: ${{ env.JJ_DIR }}jj.sh prepare
+#  build:
+#    if: ${{ !needs.prepare.outputs.workflows && needs.prepare.outputs.prefix-list-length != '0' }}
+#    needs: prepare
+#    runs-on: ubuntu-latest
+#    env:
+#      JJ_PREFIX: ""
+#      JJ_REGION: "eu-central-1"
+#      JJ_ROLE: "none"
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        tf: ${{ fromJson(needs.prepare.outputs.prefix-list) }}
+#    steps:
+#      - name: checkout
+#        uses: actions/checkout@v3
+#        with:
+#          fetch-depth: 1
+#      - name: onehundred
+#        run: ${{ env.JJ_DIR }}me.sh extractMappedValues "${{ matrix.tf }}" "${{ env.JJ_DIR }}path-prefix-aws-role-mapping.json"
+#      - name: fail if role not found
+#        if: ${{ env.JJ_ROLE == 'none' }}
+#        # TODO: create issue before exiting => should not block workflow runs
+#        run: exit 1
+#      - name: install stuff
+#        run: |
+#          brew install tfenv
+#          tfenv install 1.1.8
+#          tfenv use 1.1.8
+#      - name: yo
+#        run: |
+#          echo "${{ env.JJ_MODE }}"
+#          echo "${{ env.JJ_REGION }}"
+#          echo "${{ env.JJ_ROLE }}"
+#          echo "${{ matrix.tf }}"
+#      - name: assume role
+#        uses: aws-actions/configure-aws-credentials@v1
+#        with:
+#          role-to-assume: ${{ env.JJ_ROLE }}
+#          aws-region: ${{ env.JJ_REGION }}
+#      - name: create tf plan
+#        run: |
+#          cd ${{ matrix.tf }}
+#          terraform init
+#          terraform plan -lock=false > plan.txt
+#          cat plan.txt
+#      - name: jj-prefix
+#        run: |
+#          export JJ_TEMP=$(echo ${{ matrix.tf }} | sed -E 's%/%-%g')
+#          echo "JJ_PREFIX=$JJ_TEMP" >> "$GITHUB_ENV"
+#      - name: store tf plan
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: ${{ env.JJ_PREFIX }}plan.txt
+#          path: ${{ matrix.tf }}plan.txt
+#          retention-days: 1
